### ISSUE TITLE
Can't resolve 'firebase'

### ISSUE THREAD

**Issue by kody435** [CleverProgrammers/cp-disney-plus-clone#10]
Failed to compile.

./src/firebase.js
Module not found: Can't resolve 'firebase' in '/CP/youtube-disney-clone/src'

🔴It is showing Module not found although it is present in src folder.🔴

Image:
<img width="927" alt="Screenshot 2022-02-01 at 11 50 16 AM" src="https://user-images.githubusercontent.com/50862704/151921689-d0124359-ca91-4b4c-b1e9-0b739280be76.png">

**Comment by kody435** [comment]
Pls help me

**Comment by advaitkhawase15** [comment]
install the firebase version 8.4.1 which was used in this clone.

**Comment by BlackWatch021** [comment]
If you want to go with the latest version of firebase then use this command

1. import firebase from 'firebase/compat/app';

**Comment by BlackWatch021** [comment]
> Pls help me

If you want to go with the latest version of firebase then use this command to import firebase

1. import firebase from 'firebase/compat/app';

and you are gonna need these import too if you stick with the latest version of firebase...

1. import 'firebase/compat/auth';
2. import 'firebase/compat/firestore';
3. import 'firebase/compat/storage';

**Comment by vaibhavchobisa** [comment]
> Pls help me

Did you get a solution to this, I am facing the same problem!

**Comment by Architsharma7** [comment]
I can resolve the issue.

**Comment by 9391807200** [comment]
![2022-08-14](https://user-images.githubusercontent.com/111217623/184526158-a3780d13-d96d-4690-89bf-5d3ba5d76913.png)

**Comment by 9391807200** [comment]
I am getting this error by using npm install firebase@8.4.1 version

**Comment by Architsharma7** [comment]
You can see how to fix this issue, i have made a pull request, see into it.

**Comment by 9391807200** [comment]
![2022-08-14](https://user-images.githubusercontent.com/111217623/184526743-d7879be8-0e2f-4402-907e-1f6f0d241ffd.png)
no content is displaying it showing simply array

**Comment by 9391807200** [comment]
![2022-08-14 (1)](https://user-images.githubusercontent.com/111217623/184526786-332b4f1f-fe7e-4b82-a56c-38356ec69bd9.png)
it is showing simply array not content

**Comment by 9391807200** [comment]
> You can see how to fix this issue, i have made a pull request, see into it.

not available

**Comment by Architsharma7** [comment]
https://github.com/CleverProgrammers/cp-disney-plus-clone/pull/15

**Comment by 9391807200** [comment]
please give clear guidance

**Comment by 9391807200** [comment]
![2022-08-14 (2)](https://user-images.githubusercontent.com/111217623/184532112-127b011b-3fb7-4cca-ad58-e2fa2cb655ce.png)
it is showing simply array not content

**Comment by kody435** [comment]
Bro try to reinstalling npm package

1. Uninstall NODE_MODULES Folder.

2. Write in Terminal `
npm i` or `npm install`

**Comment by Govind783** [comment]
> I can resolve the issue.

hey, could you please help me? I'm unable to solve the error. can we get in touch via any platform LinkedIn, Twitter, or any other that your comfortable with
