### ISSUE TITLE
the video is not playing in Viewers.js 

### ISSUE THREAD

**Issue by coolveer** [CleverProgrammers/cp-disney-plus-clone#2]
```
<video autoPlay={true} loop={true} playsInline={true}>
       <source src="/videos/1608229455-star-wars.mp4" type="video/mp4" />
 </video>
```

this code adds the video but the video was not playing in crome 

the solution to this is that you just have to add muted to the video code just like this 

```
<video autoPlay={true} loop={true} playsInline={true} muted>
        <source src="/videos/1608229455-star-wars.mp4" type="video/mp4" />
</video>

```
just a little help from my side if someone gets stuck

**Comment by coolveer** [comment]
`<video autoPlay={true} loop={true} playsInline={true}>
       <source src="/videos/1608229455-star-wars.mp4" type="video/mp4" />
 </video>

this code adds the video but the video was not playing in crome 

the solution to this is that you just have to add muted to the video code just like this 

<video autoPlay={true} loop={true} playsInline={true} muted>
        <source src="/videos/1608229455-star-wars.mp4" type="video/mp4" />
</video>

just a little helo from my side is someone gets stuck `

**Comment by Faruk-Suljagic** [comment]
Can you please explain why 'muted' worked?

**Comment by jdanglade** [comment]
I would also like to know, why did 'muted' work?

**Comment by SudhanshuBlaze** [comment]
Chrome does not allow videos to autoplay if it's muted.
