### ISSUE TITLE
Please provide json file with movie data

### ISSUE THREAD

**Issue by ManuC84** [CleverProgrammers/cp-disney-plus-clone#3]
It's impossible to continue the project without the movie data you're using to populate the firestore db. Please provide the disneyPlusMoviesData.json file you're using in the video somewhere in your github repo. Thanks a lot.

**Comment by NareshKurukuti** [comment]
Hi Manu,
CP team gave disneyPlusMoviesData.json file in this location "**cp-disney-plus-clone/src/disneyPlusMoviesData.json**", can you check it once.

**Comment by ManuC84** [comment]
> Hi Manu,
> CP team gave disneyPlusMoviesData.json file in this location "**cp-disney-plus-clone/src/disneyPlusMoviesData.json**", can you check it once.

Fantastic! I hadn't seen it. Thank you very much.

**Comment by vaibhavnirmal2001** [comment]
Thanks !! this helped me too!
